/**
 * BENCHUIX-27B static identifiers.
 * @typedef {"DETECTADO"|"PROPOSTO"|"BLOQUEADO_AUTO"|"AGUARDANDO_APROVACAO"|"APROVADO"|"RECUSADO"|"COMPROVANTE_GERADO"|"ROLLBACK_DISPONIVEL"|"DESFEITO"} ActionState
 * @typedef {"NORMAL"|"MODO_DEGRADADO"} GlobalMode
 */

export const ACTION_STATES = Object.freeze({
  DETECTADO: "DETECTADO",
  PROPOSTO: "PROPOSTO",
  BLOQUEADO_AUTO: "BLOQUEADO_AUTO",
  AGUARDANDO_APROVACAO: "AGUARDANDO_APROVACAO",
  APROVADO: "APROVADO",
  RECUSADO: "RECUSADO",
  COMPROVANTE_GERADO: "COMPROVANTE_GERADO",
  ROLLBACK_DISPONIVEL: "ROLLBACK_DISPONIVEL",
  DESFEITO: "DESFEITO"
});

export const GLOBAL_MODES = Object.freeze({
  NORMAL: "NORMAL",
  MODO_DEGRADADO: "MODO_DEGRADADO"
});

export const OWNER_ACTIONS = Object.freeze({
  OWNER_PROPOSE: "OWNER_PROPOSE",
  OWNER_APPROVE: "OWNER_APPROVE",
  OWNER_REFUSE: "OWNER_REFUSE",
  OWNER_BLOCK: "OWNER_BLOCK",
  OWNER_RECEIPT: "OWNER_RECEIPT",
  OWNER_UNDO: "OWNER_UNDO",
  OWNER_OVERRIDE: "OWNER_OVERRIDE",
  OWNER_DEGRADE: "OWNER_DEGRADE",
  OWNER_RECOVER: "OWNER_RECOVER",
  OWNER_SWITCH_SCENARIO: "OWNER_SWITCH_SCENARIO",
  OWNER_NAVIGATE: "OWNER_NAVIGATE"
});

export const SCREEN_IDS = Object.freeze({
  TODAY: "today",
  APPROVE: "approve",
  HISTORY: "history",
  ROLLBACK: "rollback",
  DEGRADED: "degraded"
});

export const SCENARIO_IDS = Object.freeze({
  BARBEARIA: "barbearia_after_hours_vip_exception",
  MERCADO: "mercado_suspected_refund_declined",
  ESCRITORIO: "escritorio_attachment_intercepted"
});

