import { ACTION_STATES, GLOBAL_MODES, OWNER_ACTIONS } from "./ids.js";

export const VALID_TRANSITIONS = Object.freeze({
  [ACTION_STATES.DETECTADO]: {
    [OWNER_ACTIONS.OWNER_PROPOSE]: ACTION_STATES.PROPOSTO,
    [OWNER_ACTIONS.OWNER_BLOCK]: ACTION_STATES.BLOQUEADO_AUTO
  },
  [ACTION_STATES.PROPOSTO]: {
    [OWNER_ACTIONS.OWNER_BLOCK]: ACTION_STATES.BLOQUEADO_AUTO,
    [OWNER_ACTIONS.OWNER_REFUSE]: ACTION_STATES.RECUSADO,
    [OWNER_ACTIONS.OWNER_APPROVE]: ACTION_STATES.AGUARDANDO_APROVACAO
  },
  [ACTION_STATES.BLOQUEADO_AUTO]: {
    [OWNER_ACTIONS.OWNER_RECEIPT]: ACTION_STATES.COMPROVANTE_GERADO,
    [OWNER_ACTIONS.OWNER_OVERRIDE]: ACTION_STATES.AGUARDANDO_APROVACAO
  },
  [ACTION_STATES.AGUARDANDO_APROVACAO]: {
    [OWNER_ACTIONS.OWNER_APPROVE]: ACTION_STATES.APROVADO,
    [OWNER_ACTIONS.OWNER_REFUSE]: ACTION_STATES.RECUSADO
  },
  [ACTION_STATES.APROVADO]: {
    [OWNER_ACTIONS.OWNER_RECEIPT]: ACTION_STATES.COMPROVANTE_GERADO
  },
  [ACTION_STATES.RECUSADO]: {
    [OWNER_ACTIONS.OWNER_RECEIPT]: ACTION_STATES.COMPROVANTE_GERADO
  },
  [ACTION_STATES.COMPROVANTE_GERADO]: {
    [OWNER_ACTIONS.OWNER_UNDO]: ACTION_STATES.ROLLBACK_DISPONIVEL
  },
  [ACTION_STATES.ROLLBACK_DISPONIVEL]: {
    [OWNER_ACTIONS.OWNER_UNDO]: ACTION_STATES.DESFEITO
  },
  [ACTION_STATES.DESFEITO]: {
    [OWNER_ACTIONS.OWNER_RECEIPT]: ACTION_STATES.COMPROVANTE_GERADO
  }
});

const DEGRADED_BLOCKED_ACTIONS = new Set([
  OWNER_ACTIONS.OWNER_APPROVE,
  OWNER_ACTIONS.OWNER_OVERRIDE,
  OWNER_ACTIONS.OWNER_UNDO
]);

export function isExecutionLikeBlockedInMode(mode, actionType) {
  return mode === GLOBAL_MODES.MODO_DEGRADADO && DEGRADED_BLOCKED_ACTIONS.has(actionType);
}

export function nextActionState(currentState, actionType, mode = GLOBAL_MODES.NORMAL) {
  if (isExecutionLikeBlockedInMode(mode, actionType)) {
    return currentState;
  }
  return VALID_TRANSITIONS[currentState]?.[actionType] || currentState;
}

export function receiptRequiredForState(state) {
  return [
    ACTION_STATES.BLOQUEADO_AUTO,
    ACTION_STATES.APROVADO,
    ACTION_STATES.RECUSADO,
    ACTION_STATES.DESFEITO
  ].includes(state);
}

