import { ACTION_STATES, GLOBAL_MODES, OWNER_ACTIONS } from "../domain/ids.js";
import { nextActionState } from "../domain/stateMachine.js";

export const stateMachine_valid_transitions = [
  nextActionState(ACTION_STATES.DETECTADO, OWNER_ACTIONS.OWNER_PROPOSE) === ACTION_STATES.PROPOSTO,
  nextActionState(ACTION_STATES.PROPOSTO, OWNER_ACTIONS.OWNER_BLOCK) === ACTION_STATES.BLOQUEADO_AUTO,
  nextActionState(ACTION_STATES.AGUARDANDO_APROVACAO, OWNER_ACTIONS.OWNER_APPROVE) === ACTION_STATES.APROVADO,
  nextActionState(ACTION_STATES.RECUSADO, OWNER_ACTIONS.OWNER_RECEIPT) === ACTION_STATES.COMPROVANTE_GERADO
];

export const degraded_blocks_execution_like_controls = [
  OWNER_ACTIONS.OWNER_APPROVE,
  OWNER_ACTIONS.OWNER_OVERRIDE,
  OWNER_ACTIONS.OWNER_UNDO
].every((actionType) => nextActionState(ACTION_STATES.AGUARDANDO_APROVACAO, actionType, GLOBAL_MODES.MODO_DEGRADADO) === ACTION_STATES.AGUARDANDO_APROVACAO);

